### ISSUE TITLE
week003-docker-getting-started 里的例子Dockerfile需要更新

### ISSUE THREAD

**Issue by monocosmo** [aneasystone/weekly-practice#2]
FROM node:12-alpine
WORKDIR /app
COPY . .
RUN yarn install --production
CMD ["node", "src/index.js"]
EXPOSE 3000

node:12-alpine 版本过旧，build image 的时候会报错版本冲突，可以改成 node:20-alpine

**Comment by aneasystone** [comment]
谢谢提醒，文章写的比较久了，有时间我更新下
